sudo: required

language: generic

services:
- docker

script:
- make build

branches:
  only:
  - source

before_deploy:
- find dist -type f -name '.f' | xargs rm

deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  local-dir: dist
  target-branch: master
  fqdn: gtramontina.com
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: source

