version: "3"
services:
  build:
    image: klakegg/hugo:0.79.1-ext-alpine
    volumes:
      - .:/src
      - ./public:/target

  shell:
    image: klakegg/hugo:0.79.1-ext-alpine
    command: shell
    volumes:
      - .:/src

  server:
    image: klakegg/hugo:0.79.1-ext-alpine
    command: server -D
    volumes:
      - .:/src
    ports:
      - 1313:1313
