on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.5.6
        with:
          publish_branch: master
          publish_dir: ./output
          cname: gtramontina.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
